spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${PRODUCT_DB_URL}
    username: ${PRODUCT_DB_USER_NAME}
    password: ${PRODUCT_DB_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
server:
  port: ${PRODUCT_SERVER_PORT}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_API_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0