spring:
  application:
    name: order-service
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

